export const TASK_IDS = {
    HELLO_WEB: 'HELLO_WEB',
    CHANGE: 'CHANGE',
    LOAD_DATA: 'LOAD_DATA',
    FETCH: 'FETCH',
    ADD: 'ADD',
    SERVER: 'SERVER',
    DATABASE: 'DATABASE',
    REGISTRATION: 'REGISTRATION',
    DEPLOYMENT: 'DEPLOYMENT',
};
