export enum BattleEvent {
    CREATE_1V1 = 'CREATE_1V1',
    ROOM_NOTIFICATION = 'ROOM_NOTIFICATION',
    ERROR = 'ERROR',
    CLOSE_ROOM = 'CLOSE_ROOM',
    WIN_NOTIFICATION = 'WIN_NOTIFICATION',
    LOSE_NOTIFICATION = 'LOSE_NOTIFICATION',
}
