FROM node:20

WORKDIR /app

RUN npm install -g pnpm

COPY ./pnpm-workspace.yaml ./
COPY ./package.json ./
COPY ./pnpm-lock.yaml ./

COPY ./backend ./backend
COPY ./shared ./shared

RUN pnpm --filter backend install

RUN pnpm --filter backend build

RUN apt-get update && apt-get install -y --no-install-recommends \
    libnss3 \
    libnspr4 \
    libatk1.0-0 \
    libatk-bridge2.0-0 \
    libcups2 \
    libdrm2 \
    libatspi2.0-0 \
    libxcomposite1 \
    libxdamage1 \
    libxfixes3 \
    libxrandr2 \
    libgbm1 \
    libxkbcommon0 \
    libpango-1.0-0 \
    libcairo2 \
    libasound2 \
    libwayland-client0 \
    fonts-liberation \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*

RUN pnpm --filter backend exec playwright install --only-shell chromium

EXPOSE 3000
CMD ["pnpm", "--filter", "backend", "run", "start:dev"]
