export const hints = [
    "Read the task carefully before you start coding.",
    "Break the problem into small steps.",
    "Use console.log to understand what your code does.",
    "Check the browser console for errors.",
    "Test your code after every small change.",
    "Do not copy blindly. Try to understand the solution.",
    "Start with the simplest solution first.",
    "If something does not work, read the error message slowly.",
    "Use meaningful variable names.",
    "Keep your code clean and easy to read.",
    "A small working solution is better than a big broken one.",
    "Try to explain the code in your own words.",
    "Check if all brackets and parentheses are closed.",
    "Use comments only when they make the code easier to understand.",
    "Make sure your function names describe what they do.",
    "If you are stuck, test one part of the code at a time.",
    "Think about what should happen before writing the code.",
    "Compare the expected result with the actual result.",
    "Use the React state only for values that can change.",
    "Do not mutate state directly.",
    "Use props to pass data into components.",
    "Keep components small and focused.",
    "If a component becomes too large, split it into smaller components.",
    "Use useEffect when something should happen after rendering.",
    "Add dependencies to useEffect when the effect depends on changing values.",
    "Remember: empty dependency array means the effect runs once.",
    "Before asking for help, try to describe the problem clearly.",
    "Every bug teaches you something new.",
    "Write code step by step, not all at once.",
    "Take a short break if you are stuck too long.",
];