
export const BUG_HUNTER_PROGRESS_REPO_PORT = 'BUG_HUNTER_PROGRESS_REPO_PORT' as const;
export const CODE_EXECUTION_PORT = 'CODE_EXECUTION_PORT' as const;
export const PRACTICE_PROGRESS_REPO_PORT = 'PRACTICE_PROGRESS_REPO_PORT' as const;
export const PRACTICE_LEVEL_REPO_PORT = 'PRACTICE_LEVEL_REPO_PORT' as const;


// UC WIRING TOKENS
export const SUBMIT_BUG_HUNTER_SOLUTION_PORT = 'SUBMIT_BUG_HUNTER_SOLUTION_PORT' as const;
export const GET_PRACTICE_PROGRESS_REPO_PORT = 'GET_PRACTICE_PROGRESS_REPO_PORT' as const;
export const GET_PRACTICE_LEVEL_PORT = 'GET_PRACTICE_LEVEL_PORT' as const;
export const SUBMIT_PRACTICE_SOLUTION_PORT = 'SUBMIT_PRACTICE_SOLUTION_PORT' as const