import { HttpStatus } from '@nestjs/common';
import { ErrorCode } from '@funcode/shared';

export const ERROR_CODE_TO_HTTP_STATUS: Record<ErrorCode, HttpStatus> = {
    INTERNAL_SERVER_ERROR: HttpStatus.INTERNAL_SERVER_ERROR,

    FRIENDSHIP_ALREADY_EXISTS: HttpStatus.CONFLICT,
    FRIEND_REQUEST_ALREADY_EXISTS: HttpStatus.CONFLICT,
    EMAIL_ALREADY_EXISTS: HttpStatus.CONFLICT,
    USERNAME_ALREADY_EXISTS: HttpStatus.CONFLICT,
    CLAN_NAME_ALREADY_EXISTS: HttpStatus.CONFLICT,
    USER_ALREADY_IN_CLAN: HttpStatus.CONFLICT,

    INVALID_CREDENTIALS: HttpStatus.UNAUTHORIZED,

    INVITE_CODE_NOT_FOUND: HttpStatus.NOT_FOUND,
    BUG_HUNTER_LEVEL_NOT_FOUND: HttpStatus.NOT_FOUND,
    NOT_FOUND_PROGRESS_ID: HttpStatus.NOT_FOUND,
    LEVEL_NOT_FOUND: HttpStatus.NOT_FOUND,
    CLAN_NOT_FOUND: HttpStatus.NOT_FOUND,
    FRIEND_REQUEST_NOT_FOUND: HttpStatus.NOT_FOUND,
    USER_NOT_FOUND: HttpStatus.NOT_FOUND,
    FRIENDSHIP_NOT_FOUND: HttpStatus.NOT_FOUND,

    SELF_FRIEND_REQUEST: HttpStatus.BAD_REQUEST,
    INVALID_EMAIL: HttpStatus.BAD_REQUEST,
    INVALID_PASSWORD: HttpStatus.BAD_REQUEST,
    INVALID_USERNAME: HttpStatus.BAD_REQUEST,
    UNSUPPORTED_LANGUAGE: HttpStatus.BAD_REQUEST,

    BUG_HUNTER_LEVEL_LOCKED: HttpStatus.FORBIDDEN,
    BUG_HUNTER_LEVEL_NOT_SUBMITTABLE: HttpStatus.FORBIDDEN,
    FRIEND_REQUEST_ACCESS_DENIED: HttpStatus.FORBIDDEN,
};