export const MATCHMAKING_QUEUE_PORT = 'MATCHMAKING_QUEUE_PORT' as const;
export const REDIS_CLIENT = 'REDIS_CLIENT' as const;
export const JOIN_MATCHMAKING_SERVICE = 'JOIN_MATCHMAKING_SERVICE' as const;
export const BATTLE_REPOSITORY_PORT = 'BATTLE_REPOSITORY_PORT' as const;
