export const REDIS_MATCHMAKING_ADAPTER = 'REDIS_MATCHMAKING_ADAPTER' as const;
export const REDIS_CLIENT = 'REDIS_CLIENT' as const;
export const JOIN_MATCHMAKING_SERVICE = 'JOIN_MATCHMAKING_SERVICE' as const;
