export const CLASSIC_TASK_REPOSITORY_PORT = 'CLASSIC_TASK_REPOSITORY_PORT' as const;
export const BUG_HUNTER_TASK_REPOSITORY_PORT = 'BUG_HUNTER_TASK_REPOSITORY_PORT' as const;
export const BATTLE_REPOSITORY_PORT = 'BATTLE_REPOSITORY_PORT' as const;
export const ARENA_TASK_PROVIDER_PORT = 'ARENA_TASK_PROVIDER_PORT' as const;
