export enum SOCKET_EVENTS {
    MATCH_FOUND = 'MATCH_FOUND',
    BATTLE_STARTED = 'BATTLE_STARTED',
    PLAYER_READY = 'PLAYER_READY',
    SUBMIT_SOLUTION = 'SUBMIT_SOLUTION',
    WRONG_SUBMIT = 'WRONG_SUBMIT',
    JOIN_MATCHMAKING = 'JOIN_MATCHMAKING',
    LEAVE_MATCHMAKING = 'LEAVE_MATCHMAKING',
    BATTLE_ABORTED = 'BATTLE_ABORTED',
    WIN = 'WIN',
    LOSE = 'LOSE',
    ERROR = 'ERROR',
    CODE_GOLF_SUBMIT_RESULT = 'CODE_GOLF_SUBMIT_RESULT',

}
