export const JOIN_MATCHMAKING_PORT = 'JOIN_MATCHMAKING_PORT' as const;
export const LEAVE_MATCHMAKING_PORT = 'LEAVE_MATCHMAKING_PORT' as const;
export const BATTLE_MANAGER_PORT = 'BATTLE_MANAGER_PORT' as const;
export const CLASSIC_VALIDATOR_PORT = 'CLASSIC_VALIDATOR_PORT' as const;
export const MATCH_MAKER_PORT = 'MATCH_MAKER_PORT' as const;
export const SUBMIT_ARENA_SOLUTION_PORT = 'SUBMIT_ARENA_SOLUTION_PORT' as const;
export const BUG_HUNTER_VALIDATOR_PORT = 'BUG_HUNTER_VALIDATOR_PORT' as const;
